### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by stgm** [minprog/assist#1]
Verwachting: groot deel van de studenten aanwezig, deel soms thuis. Assistenten zijn niet altijd aanwezig/bereikbaar.

Slack hebben we gebruikt voor de bereikbaarheid van de assistent. Is dit nodig? Willen we dit? We hebben genoeg georganiseerde contacten (werkgroep, feedback) dus misschien beter om het niet te doen (in het kader van de _werkdruk_ voor assistenten, die soms wel gemeld is).

Belangrijkste wat dan ontbreekt is manier voor assistenten om mededelingen naar studenten te sturen. Dit kan ik bv. in de website bouwen? Hoewel veel assistenten ook weten hoe ze dat via datanose moeten doen.

@Jelleas

**Comment by Jelleas** [comment]
Wel doen. Erg makkelijk voor zaken als ziekmelden en voor de hele groep vragen beantwoorden. Ook goed voor studentencontact onderling.

Wel **benadrukken** dat de assistent niet altijd beschikbaar is en het heel normaal is om te moeten wachten.

**Comment by Jelleas** [comment]
assistenten moeten ook echt werktijden instellen in slack, dus echt geen notificaties buiten X - X uur

**Comment by stgm** [comment]
Nog niet erg overtuigend :-) We moeten dit even per vak doornemen denk ik.

**Comment by stgm** [comment]
Werktijden van assistenten zijn overigens niet X-X uur maar "tijdens het assisteren", "tijdens de werkgroep" en "tijdens het nakijken". Iets om over na te denken.

**Comment by Jelleas** [comment]
Voorheen hebben we wel loze tijd ingepland juist voor zaken zoals Slack. Is dat niet logischer?

**Comment by stgm** [comment]
Ik heb het behouden ivm mogelijk veel mensen die verkouden afwezig zullen moeten zijn.
